### ISSUE TITLE
[Enhancement] Language selection list

### ISSUE THREAD

**Issue by DraconicNEO** [HowlingWolfHWC/HWC-Language-Selector#1]
Hello, I feel like it would be a very good idea to replace the system where languages are mapped to buttons with a List menu for language selection.

**Comment by HowlingWolfHWC** [comment]
It will certainly be better, but since this is a simple PoC, I will not do a menu.
If you want to, you can code it easily. Submit a pull request and I will gladly merge it and compile a new version.

XtremeEliteBoot+ will feature system language selection on the menu itself:
![image](https://user-images.githubusercontent.com/58843152/139370650-27b44a9a-0396-4c8a-8f1b-d307f701902b.png)
And, from there, you will be able to launch any homebrew you want:
![image](https://user-images.githubusercontent.com/58843152/139370680-8d595a08-d928-4e2e-99c1-731a3e1c2516.png)
Same goes to disc games:
![image](https://user-images.githubusercontent.com/58843152/139370734-56ca4382-f68e-41d0-a797-0402fd0b404b.png)
If you want a menu, please, wait for XEB+ to be released, hopefully, soon...

**Comment by HowlingWolfHWC** [comment]
I think the new update will make your dreams come true...
https://www.psx-place.com/resources/hwcs-language-selector.1191/
